### ISSUE TITLE
Mirror without discarding history?

### ISSUE THREAD

**Issue by takluyver** [pygame/pygamemirror#1]
This mirror only has one commit, which gets replaced every time it updates. Using [hg-git](http://hg-git.github.io/), it should be possible to mirror the repo in a way that preserves the record of how it has changed.

I've just set this repo up to demonstrate the principle. This took maybe 10 minutes, and I've never used hg-git before:
https://github.com/takluyver/pygame-mirror-test

**Comment by illume** [comment]
There were some crashes with the history, which is why it was removed. I think with launchpad.

**Comment by illume** [comment]
Did you need the history for anything?

**Comment by takluyver** [comment]
I don't particularly need the history, but I'd guess that this also doesn't copy across tags from hg? With the current Travis setup, you need a tag in Github to get the wheels back out.

Mostly it just seems like an odd way of mirroring to Github; most mirrors I've seen (e.g. [Python itself](https://github.com/python/cpython)) do mirror the full history, and as far as I can tell, it's not a terribly difficult thing to do.

**Comment by illume** [comment]
The only reason for removing the history was because launchpad choking on the repo when it had history. I'm not sure if that's still the case.

I'll set up one with full history too.

**Comment by takluyver** [comment]
Thanks. I'm happy to help maintain that if you want to put the scripts you use in another repo and/or give me access to the server where it runs.

**Comment by illume** [comment]
Ok, great. I'll add that script into the pygameweb repo soon.
